# .github/workflows/douban.yml
name: douban
on: 
  schedule:
  - cron: "*/30 * * * *"

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 181637001
        type: movie
        format: notion
        dir: 76ed830e50f24ae8a63ce36c1515cd08
        notion_token: ${{ secrets.notion_token }}
